# Generated by Django 3.0.7 on 2020-12-28 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('course_title', models.CharField(blank=True, default='', max_length=100)),
                ('course_phases', models.CharField(blank=True, default="['Lobby Start', 'Warmup', 'Push', 'Cooldown', 'Lobby End']", max_length=500)),
                ('course_phases_timed', models.CharField(blank=True, default="['Warmup', 'Push', 'Intensity', 'Cooldown']", max_length=500)),
                ('course_phases_nontimed', models.CharField(blank=True, default="['Lobby Start', 'Lobby End']", max_length=500)),
                ('course_starttime', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_runtime', models.IntegerField(default=0)),
                ('course_runtime_formatted', models.CharField(blank=True, default='00:00', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('participation_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('participation_course_phase', models.IntegerField(default=0)),
                ('participation_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
