# Generated by Django 3.0.7 on 2020-10-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201025_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='participation_course_phase',
            field=models.IntegerField(default=0),
        ),
    ]
