# Generated by Django 3.0.7 on 2020-11-15 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20201115_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='participation_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='participation_participation_created', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
