# Generated by Django 3.0.7 on 2020-11-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201115_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='participation_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
