# Generated by Django 3.0.7 on 2020-12-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201213_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_starttime',
            field=models.DateTimeField(default='2020-12-13 23:28:11'),
        ),
    ]
