# Generated by Django 3.0.7 on 2020-12-19 10:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201218_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_starttime',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 19, 10, 13, 12, 383350, tzinfo=utc)),
        ),
    ]
