# Generated by Django 3.0.7 on 2020-12-19 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201219_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_starttime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
