# Generated by Django 3.0.7 on 2020-12-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201219_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_phases_nontimed',
            field=models.CharField(blank=True, default="['Lobby Start', 'Lobby End']", max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='course_phases_timed',
            field=models.CharField(blank=True, default="['Warmup', 'Push', 'Cooldown'", max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_phases',
            field=models.CharField(blank=True, default="['Lobby Start', 'Warmup', 'Push', 'Cooldown', 'Lobby End']", max_length=500),
        ),
    ]
