# Generated by Django 3.0.7 on 2020-12-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201223_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='participations',
        ),
    ]
